[build-system]
requires = ["setuptools", "wheel", "Cython", "numpy"]

[project]
name = "pyfindmaxima"
version = "0.1"
description = "Find local maxima in a 2D image, similar to ImageJ Find Maxima."
dependencies = [
    "numpy"
]
license = {file = "LICENSE"}