name: deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:    
  deploy:
      # this will run when you have tagged a commit, starting with "v*"
      # and requires that you have put your twine API key in your 
      # github secrets (see readme for details)
      needs: [test]
      runs-on: ubuntu-latest
      if: contains(github.ref, 'tags')
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.x"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -U setuptools setuptools_scm wheel twine Cython

        - name: Build manylinux Python wheels
          uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2010_x86_64
          with:
            python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
            build-requirements: 'cython numpy'

        - name: Build and publish
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
          run: |
            git tag
            twine upload dist/*